#!/bin/sh

#config file path:
source /usr/local/bin/display_settings.conf
sed -i '/^workspace .* output .*$/d' ~/.config/i3/config
echo "workspace \$ws1 output $Television" >> ~/.config/i3/config
echo "workspace \$ws2 output $Television" >> ~/.config/i3/config
echo "workspace \$ws3 output $Stand" >> ~/.config/i3/config
echo "workspace \$ws4 output $Television" >> ~/.config/i3/config
echo "workspace \$ws5 output $Television" >> ~/.config/i3/config
echo "workspace \$ws6 output $Television" >> ~/.config/i3/config
echo "workspace \$ws7 output $Television" >> ~/.config/i3/config
echo "workspace \$ws8 output $Television" >> ~/.config/i3/config
echo "workspace \$ws9 output $Television" >> ~/.config/i3/config
echo "workspace \$ws10 output $Television" >> ~/.config/i3/config
echo "workspace \$ws11 output $Television" >> ~/.config/i3/config
i3-msg reload
sleep 1
#xrandr settings
xrandr --output $Television --mode 1920x1080 --pos 0x0 --rotate normal \
       --output $RightLG --off \
	   --output $LeftLG --off \
	   --output $HUD --off \
	   --output $Vertical --off \
	   --output $Standing --primary --mode 1920x1080 --pos 1920x0 --rotate normal \
&&
sleep 1 \
&& feh --bg-fill ~/.images/orangeSpaceCatUp.jpg
