#!/bin/bash
#xrandr --output DisplayPort-0 --off --output DisplayPort-1 --off --output DisplayPort-2 --off --output HDMI-A-0 --mode 1920x1080 --pos 0x0 --rotate right --output DisplayPort-1-3 --off --output DisplayPort-1-4 --off --output DisplayPort-1-5 --off --output HDMI-A-1-1 --primary --mode 1920x1080 --pos 0x0 --rotate right --output DVI-D-1-0 --off

#!/bin/bash
xrandr --output DisplayPort-0 --mode 2560x1440 --pos 0x1080 --rotate normal --output DisplayPort-1 --off --output DisplayPort-2 --primary --mode 2560x1440 --pos 2560x1080 --rotate normal --output HDMI-A-0 --mode 1920x1080 --pos 640x0 --rotate normal --output DisplayPort-1-3 --mode 1920x1080 --pos 2880x0 --rotate normal --output DisplayPort-1-4 --off --output DisplayPort-1-5 --off --output HDMI-A-1-1 --mode 1920x1080 --pos 5120x600 --rotate left --output DVI-D-1-0 --mode 1920x1080 --pos 5120x600 --rotate left

