#!/bin/sh
xrandr --output DisplayPort-0 --off --output DisplayPort-1 --off --output DisplayPort-2 --primary --mode 2560x1440 --pos 0x0 --rotate normal --output HDMI-A-0 --off --output DisplayPort-1-3 --off --output DisplayPort-1-4 --off --output DisplayPort-1-5 --off --output HDMI-A-1-1 --off --output DVI-D-1-0 --off && sleep 1 && feh --bg-fill ~/.images/orangeSpaceCatUp.jpg
