#!/bin/sh

#config file path:
source /usr/local/bin/display_settings.conf
sed -i '/^workspace .* output .*$/d' ~/.config/i3/config
echo "workspace \$ws1 output $RightLG" >> ~/.config/i3/config
echo "workspace \$ws2 output $LeftLG" >> ~/.config/i3/config
echo "workspace \$ws3 output $HUD" >> ~/.config/i3/config
echo "workspace \$ws4 output $RightLG" >> ~/.config/i3/config
echo "workspace \$ws5 output $RightLG" >> ~/.config/i3/config
echo "workspace \$ws6 output $HUD" >> ~/.config/i3/config
echo "workspace \$ws7 output $Television" >> ~/.config/i3/config
echo "workspace \$ws8 output $Vertical" >> ~/.config/i3/config
echo "workspace \$ws9 output $Vertical" >> ~/.config/i3/config
echo "workspace \$ws10 output $LeftLG" >> ~/.config/i3/config
echo "workspace \$ws11 output $Vertical" >> ~/.config/i3/config
i3-msg reload
#xrandr settings
xrandr --output $Television --mode 1920x1080 --pos 640x0 --rotate normal \
	   --output $LeftLG --mode 2560x1440 --pos 0x1080 --rotate normal \
	   --output $RightLG --primary --mode 1920x1080 --pos 2560x1080 --rotate normal \
	   --output $HUD --mode 1920x1080 --pos 2560x0 --rotate normal \
	   --output $Vertical --mode 1920x1080 --pos 4480x600 --rotate left \
	   --output $Standing --mode 1920x1080 --pos 2560x1080 --rotate normal \
&&
sleep 1 \
&& feh --bg-fill ~/.images/orangeSpaceCatUp.jpg
