#!/bin/sh

#config file path:
source /usr/local/bin/display_settings.conf

#xrandr settings
xrandr --output $Television --mode 1920x1080 --pos 0x0 --rotate normal \
	   --output $LeftLG --off \
	   --output $RightLG --off \
	   --output $HUD --off \
	   --output $Vertical --off \
	   --output $Standing --primary --mode 1920x1080 --pos 0x0 --rotate normal \
&&
sleep 1 \
&& feh --bg-fill ~/.images/orangeSpaceCatUp.jpg
