#!/bin/sh

#config file path:
source /usr/local/bin/display_settings.conf
sed -i '/^workspace .* output .*$/d' ~/.config/i3/config 
echo "workspace \$ws1 output $LeftLG" >> ~/.config/i3/config
echo "workspace \$ws2 output $LeftLG" >> ~/.config/i3/config
echo "workspace \$ws3 output $LeftLG" >> ~/.config/i3/config
echo "workspace \$ws4 output $LeftLG" >> ~/.config/i3/config
echo "workspace \$ws5 output $LeftLG" >> ~/.config/i3/config
echo "workspace \$ws6 output $LeftLG" >> ~/.config/i3/config
echo "workspace \$ws7 output $Television" >> ~/.config/i3/config
echo "workspace \$ws8 output $LeftLG" >> ~/.config/i3/config
echo "workspace \$ws9 output $LeftLG" >> ~/.config/i3/config
echo "workspace \$ws10 output $LeftLG" >> ~/.config/i3/config
echo "workspace \$ws11 output $Vertical" >> ~/.config/i3/config
i3-msg reload

xrandr --output $LeftLG --primary --mode 2560x1440 --pos 0x1080 --rotate normal \
	   --output $Television --mode 1920x1080 --pos 640x0 --rotate normal \
	   --output $RightLG --off \
	   --output $HUD --off \
	   --output $Vertical --off \
	   --output $Standing --off
sleep 1 \
&& feh --bg-fill ~/.images/orangeSpaceCatUp.jpg
